<a href="https://colab.research.google.com/github/Suganya321-web/sugan/blob/main/Data-Sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import sqlite3
file_name = '/content/Data Analysis.csv'

df = pd.read_csv(file_name)
print("Data loaded. Shape:", df.shape)
df.head()

Data loaded. Shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [16]:
conn = sqlite3.connect(':memory:')
df.to_sql('data', conn, index=False, if_exists='replace')

def sql(query):
    return pd.read_sql_query(query, conn)

print("Table 'data' ready. Columns:", list(df.columns))

Table 'data' ready. Columns: ['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

In [18]:

sql("""SELECT *, (Quantity * UnitPrice) AS TotalAmount FROM data WHERE (Quantity * UnitPrice) > 1000 LIMIT 10""")
sql("""SELECT CustomerID, COUNT(*) AS total_orders FROM data GROUP BY CustomerID ORDER BY total_orders DESC""")
sql("""SELECT Product, SUM(Quantity * UnitPrice) AS total_sales FROM data GROUP BY Product ORDER BY total_sales DESC""")

sql("""SELECT AVG(Quantity * UnitPrice) AS avg_order_value FROM data""")

sql("""SELECT *, (Quantity * UnitPrice) AS TotalAmount FROM data ORDER BY TotalAmount DESC LIMIT 5""")

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,TotalAmount
0,ORD200789,2023-08-17,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40,3456.40
1,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,None,Facebook,3390.95,3390.95
2,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80,3390.80
3,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,None,Facebook,3384.90,3384.90
4,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20,3370.20